# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 991e147ae1dfd45323285922d0895ce6ba25dc3acd98736598a7f1272fdbe1ad6db2f2665b2b81ec9d60d0bcc85c2a09636a503ed45c3834d7c72d731d345ae2

test:
  secret_key_base: 6190439f280b38ae0388979efb9aa4bb4fd5f8bb81dee0a83f787051018c6061ab377a1f54f8b2c818c3230ad539711187f679c6aab0221b50a49f8b1a7fb0a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
